In [10]:
import pandas as pd
import numpy as np

In [11]:
work_sheet = pd.read_excel('.\\data\\CHN_IOtable_2020.xlsx', sheet_name = 'IOdata_q1_q2')
work_sheet

代码         部门名称           农产品           林产品          畜牧产品  \
0    01001          农产品  8.165902e+07  0.000000e+00  2.891219e+07   
1    02002          林产品  1.430682e+02  3.546732e+06  0.000000e+00   
2    03003         畜牧产品  1.492431e+02  0.000000e+00  2.273517e+07   
3    04004          渔产品  0.000000e+00  0.000000e+00  0.000000e+00   
4    05005  农、林、牧、渔服务产品  1.485717e+07  6.999667e+06  7.738022e+05   
..     ...          ...           ...           ...           ...   
148  88145         文化艺术  1.668052e+04  1.085133e+04  3.777533e+03   
149  89146           体育  0.000000e+00  0.000000e+00  0.000000e+00   
150  90147           娱乐  1.734330e+03  4.608086e+03  7.285562e+02   
151  94148         社会保障  1.271682e+03  9.592949e+03  3.979208e+03   
152  91149    公共管理和社会组织  1.271180e+05  1.095636e+05  8.665130e+04   

              渔产品   农、林、牧、渔服务产品      煤炭开采和洗选产品    石油和天然气开采产品     黑色金属矿采选产品  \
0    1.003088e+06  6.240358e+06       0.000000      0.000000      0.000000   
1    0.000000e+00  2.852046e+05  203490.684084   2231.126620   4514.977143   
2    0.000000e+00  1.888112e+06       0.000000      0.000000      0.000000   
3    3.757309e+06  7.001226e+05       0.000000      0.000000      0.000000   
4    4.114588e+06  5.660937e+06       0.000000      0.000000      0.000000   
..            ...           ...            ...           ...           ...   
148  1.999774e+04  1.134869e+04   26511.912052  31436.807165   5573.993893   
149  0.000000e+00  0.000000e+00       0.000000      0.000000      0.000000   
150  1.491798e+03  1.489096e+03  128281.474263  37931.377240  48240.834794   
151  1.771377e+03  2.191968e+03   38639.218870  20873.191887   5345.321801   
152  5.210617e+04  1.937154e+04   27115.485922   1474.614935   8761.970722   

     ...           社会保障     公共管理和社会组织      农村居民消费支出      城镇居民消费支出  \
0    ...       0.000000  0.000000e+00  5.803184e+07  1.003748e+08   
1    ...       0.000000  0.000000e+00  9.415653e+05  1.586888e+06   
2    ...       0.000000  0.000000e+00  4.091470e+07  6.822156e+07   
3    ...       0.000000  0.000000e+00  9.857348e+06  5.087177e+07   
4    ...       0.000000  0.000000e+00  0.000000e+00  0.000000e+00   
..   ...            ...           ...           ...           ...   
148  ...     731.741577  8.640198e+05  1.144144e+06  8.206004e+06   
149  ...       0.000000  0.000000e+00  1.866977e+05  3.072978e+06   
150  ...    4510.878392  8.129790e+05  4.100476e+06  2.071336e+07   
151  ...  119262.809153  1.309788e+05  0.000000e+00  0.000000e+00   
152  ...    2375.011717  2.070832e+07  5.345552e+05  5.826249e+06   

           政府消费支出      固定资本形成总额          存货变动            出口            进口  \
0    0.000000e+00  0.000000e+00  1.736387e+07  1.497113e+07  4.953507e+07   
1    0.000000e+00  0.000000e+00  1.460569e+06  3.614915e+05  8.124180e+06   
2    0.000000e+00  1.756383e+07  3.621604e+07  8.175527e+05  2.317884e+06   
3    0.000000e+00  1.350699e+04 -1.389795e+05  2.021496e+06  4.284899e+06   
4    1.963963e+07  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
..            ...           ...           ...           ...           ...   
148  1.665424e+07  0.000000e+00  0.000000e+00  1.466069e+05  1.341882e+06   
149  1.350526e+07  0.000000e+00  0.000000e+00  1.273251e+05  1.165396e+06   
150  0.000000e+00  0.000000e+00  0.000000e+00  5.468952e+05  4.091566e+06   
151  1.119233e+07  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
152  7.448911e+08  0.000000e+00  0.000000e+00  1.734244e+06  2.461523e+06   

              总产出  
0    7.078897e+08  
1    6.048506e+07  
2    3.648924e+08  
3    1.281178e+08  
4    7.029833e+07  
..            ...  
148  3.113296e+07  
149  1.741278e+07  
150  5.037401e+07  
151  1.367741e+07  
152  7.808648e+08  

[153 rows x 163 columns]

In [13]:
# convert df to array
array_intermediateGoods = work_sheet.iloc[:,2:155].values #.iloc[:,] all rows, 2:154 cols,shape(153, 153)
array_finalUse = work_sheet.iloc[:,155:161].values # shape(153, 6)
array_imports = work_sheet.iloc[:,161].values      # shape(153,1)
array_totalOutput = work_sheet.iloc[:,162].values  # shape(153,1)
#direct consumption coefficients
a_ij_matrix = array_intermediateGoods / array_totalOutput
array_finalUse

array([[ 5.80318356e+07,  1.00374794e+08,  0.00000000e+00,
         0.00000000e+00,  1.73638725e+07,  1.49711322e+07],
       [ 9.41565345e+05,  1.58688777e+06,  0.00000000e+00,
         0.00000000e+00,  1.46056919e+06,  3.61491531e+05],
       [ 4.09147029e+07,  6.82215568e+07,  0.00000000e+00,
         1.75638326e+07,  3.62160395e+07,  8.17552734e+05],
       [ 9.85734759e+06,  5.08717657e+07,  0.00000000e+00,
         1.35069882e+04, -1.38979497e+05,  2.02149559e+06],
       [ 0.00000000e+00,  0.00000000e+00,  1.96396276e+07,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 7.53293483e+05,  4.68986096e+05,  0.00000000e+00,
         0.00000000e+00, -2.62761464e+06,  2.60795536e+05],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  2.88640908e+05,  1.08531743e+06],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.19010600e+06,  1.05212273e+06],
       [ 0.00000000e+00,  0.00000000e+00,  0.000

In [14]:
# 2 calculate complete consumption coefficient
# 2.1 create a (153, 153) identity matrix 
I = np.eye(153)
# 2.2 leontief matrix
leontief = I - a_ij_matrix
# 2.3 inversed leotief matrix (I - a_ij)^-1
leontief_minus = np.linalg.solve(leontief,I)   
#leontief_inverse = np.linalg.inv(leontief)
#leontief_pinv = np.linalg.pinv(leontief)
# 2.4 complete consumption coefficient matrix (optional)
b_ij_matrix = leontief_minus - I

leontief_minus

array([[1.14287067e+00, 2.95522146e-02, 2.44829068e-01, ...,
        5.73925496e-02, 1.14819937e-02, 1.93905605e-02],
       [9.86854911e-04, 1.06378890e+00, 6.40162529e-04, ...,
        1.95305467e-03, 1.04732764e-03, 2.91693140e-03],
       [1.71919969e-03, 5.82785467e-03, 1.07017816e+00, ...,
        1.12960504e-02, 3.11525816e-03, 4.92959708e-03],
       ...,
       [6.97942738e-04, 8.92120827e-04, 6.39655442e-04, ...,
        1.03441278e+00, 1.33215040e-03, 2.46528651e-03],
       [7.82104566e-05, 2.39312260e-04, 7.18470099e-05, ...,
        1.60365754e-04, 1.00883685e+00, 2.72860467e-04],
       [4.31689957e-04, 2.24205908e-03, 5.59468764e-04, ...,
        8.56970964e-04, 4.15763468e-04, 1.02769928e+00]])

In [15]:
# an endogenous output model: output = (finaluse - import) * (I - aij)^-1
endo_output = np.sum(leontief_minus * (np.sum(array_finalUse, axis = 1) - array_imports), axis = 1)
endo_output

array([7.07889674e+08, 6.04850592e+07, 3.64892383e+08, 1.28117802e+08,
       7.02983319e+07, 2.35072612e+08, 1.07689567e+08, 6.06257963e+07,
       4.95512456e+07, 8.33575573e+07, 2.02367744e+07, 1.32848437e+08,
       1.10454593e+08, 9.11445981e+07, 1.23453549e+07, 1.93266650e+08,
       5.26720920e+07, 1.18109111e+08, 3.51203962e+07, 4.44344359e+07,
       3.33254090e+07, 1.35238255e+08, 9.32238760e+07, 6.42363767e+07,
       2.82606513e+07, 1.06682563e+08, 2.30264566e+08, 2.41376249e+07,
       2.17941791e+07, 3.46648188e+07, 7.59671458e+07, 2.21034634e+08,
       7.90185029e+07, 7.05054551e+07, 1.63638485e+08, 1.01774695e+08,
       1.78603715e+08, 9.57952157e+07, 5.13274188e+07, 1.02666417e+08,
       3.51006631e+08, 5.83266531e+07, 2.27054472e+08, 6.65395160e+07,
       2.79054368e+07, 6.62035352e+07, 1.73515140e+08, 1.81960050e+08,
       3.87373717e+07, 3.00056137e+08, 7.31810710e+07, 8.59732827e+07,
       2.72218297e+08, 1.43713366e+08, 1.97058679e+08, 1.29548547e+08,
      

In [16]:
array_totalOutput

array([7.07889674e+08, 6.04850592e+07, 3.64892383e+08, 1.28117802e+08,
       7.02983319e+07, 2.35072612e+08, 1.07689567e+08, 6.06257963e+07,
       4.95512456e+07, 8.33575573e+07, 2.02367744e+07, 1.32848437e+08,
       1.10454593e+08, 9.11445981e+07, 1.23453549e+07, 1.93266650e+08,
       5.26720920e+07, 1.18109111e+08, 3.51203962e+07, 4.44344359e+07,
       3.33254090e+07, 1.35238255e+08, 9.32238760e+07, 6.42363767e+07,
       2.82606513e+07, 1.06682563e+08, 2.30264566e+08, 2.41376249e+07,
       2.17941791e+07, 3.46648188e+07, 7.59671458e+07, 2.21034634e+08,
       7.90185029e+07, 7.05054551e+07, 1.63638485e+08, 1.01774695e+08,
       1.78603715e+08, 9.57952157e+07, 5.13274188e+07, 1.02666417e+08,
       3.51006631e+08, 5.83266531e+07, 2.27054472e+08, 6.65395160e+07,
       2.79054368e+07, 6.62035352e+07, 1.73515140e+08, 1.81960050e+08,
       3.87373717e+07, 3.00056137e+08, 7.31810710e+07, 8.59732827e+07,
       2.72218297e+08, 1.43713366e+08, 1.97058679e+08, 1.29548547e+08,
      

In [17]:
endo_output - array_totalOutput

array([-2.38418579e-07, -1.11758709e-07,  0.00000000e+00, -8.94069672e-08,
       -5.96046448e-08,  1.19209290e-07,  2.98023224e-07,  1.93715096e-07,
        1.19209290e-07,  1.49011612e-07,  3.35276127e-08, -1.49011612e-08,
       -1.04308128e-07, -7.45058060e-08,  1.30385160e-08, -1.19209290e-07,
        1.49011612e-08,  1.04308128e-07, -3.72529030e-08,  5.21540642e-08,
       -1.86264515e-08,  5.96046448e-08,  5.96046448e-08,  7.45058060e-09,
        2.60770321e-08,  5.96046448e-08, -1.19209290e-07,  1.49011612e-08,
       -1.11758709e-08, -3.72529030e-08,  4.47034836e-08, -1.49011612e-07,
       -2.98023224e-08,  0.00000000e+00,  1.49011612e-07,  5.96046448e-08,
        0.00000000e+00, -1.49011612e-08,  2.98023224e-08,  0.00000000e+00,
       -5.96046448e-07, -7.45058060e-08,  1.49011612e-07, -7.45058060e-09,
       -8.19563866e-08,  7.45058060e-09, -1.19209290e-07, -1.49011612e-07,
       -2.23517418e-08,  4.17232513e-07,  1.49011612e-08, -1.49011612e-08,
       -1.78813934e-07,  

In [25]:
# a change in final use -->  change in output?
# mathematical expression: delta_output = (I - aij)^-1 * delta_finalUse
# 3. question: increasing the final use of sector 2 ("林产品") by 1 million CNY ---> output
shock_array = np.zeros((153,1)) # init an array with 0s
row_index = 1  # row to replace (sector 2, index starts from 0)
shock_value = 100 
shock_array[row_index] = shock_value
shock_array

array([[  0.],
       [100.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  

In [26]:
# result
new_output = np.sum(leontief_minus * ((np.sum(array_finalUse, axis = 1) + shock_array - array_imports)), axis = 1)

new_output - endo_output


array([  0.        , 223.45456874,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.  